package com.cb.kanbanbackend;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

//automatically generated by Spring

@SpringBootTest
class KanbanBackendApplicationTests {

    @Test
    void contextLoads() {
    }

}
